{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.exifinterface",
    "module": "exifinterface",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13292951"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exifinterface-1.4.1-sources.jar",
          "url": "exifinterface-1.4.1-sources.jar",
          "size": 73275,
          "sha512": "872445a8c34bb27b344f4afd13e44414d3250c156b3541db21fc183c484d535bf02892de83d47eff1344b6f6f21c05560e69b033d8546843dc5874d88b662aef",
          "sha256": "6451ce7b1d935c8d295bc704ae4cc9c1c1ef890ccf61dca65dccd17980990997",
          "sha1": "4b03f6fec245e87c119f7aa271ee6c592966acae",
          "md5": "2b3ae54219ef76514dbd60dd61f35979"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "exifinterface-1.4.1.aar",
          "url": "exifinterface-1.4.1.aar",
          "size": 75523,
          "sha512": "402bbc94498c937bbfcac17340208e0b5d11101f85d2b6418a46f5d4c8f07169f1038c56f2c065e825ba0da77f2059e0532a37d1dd40408610d85c0fa6fa10b0",
          "sha256": "17e17a6b86bb54074d3a7ecfa695ab920eaff4cf667a8371ed82e377580cfcf6",
          "sha1": "d8336b7d7dfd354f334dd21372db9e9e2da2fd81",
          "md5": "29eed35cb6ae6755d55b8a4d911498fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "exifinterface-1.4.1.aar",
          "url": "exifinterface-1.4.1.aar",
          "size": 75523,
          "sha512": "402bbc94498c937bbfcac17340208e0b5d11101f85d2b6418a46f5d4c8f07169f1038c56f2c065e825ba0da77f2059e0532a37d1dd40408610d85c0fa6fa10b0",
          "sha256": "17e17a6b86bb54074d3a7ecfa695ab920eaff4cf667a8371ed82e377580cfcf6",
          "sha1": "d8336b7d7dfd354f334dd21372db9e9e2da2fd81",
          "md5": "29eed35cb6ae6755d55b8a4d911498fc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "exifinterface-1.4.1-versionMetadata.json",
          "url": "exifinterface-1.4.1-versionMetadata.json",
          "size": 18300,
          "sha512": "06c867f38fe901e5101da5eff834b20d845bae49ea6fe073d62421c8737d6128ef05c0580db4c680dfaddd14b0c89aaa98c5e1572627dd0ab1b99b4af26cb3ce",
          "sha256": "15162b9188690985ff1ba470b6aae0928209890f48774f4e42580aceae9e855c",
          "sha1": "b3127e3a401a1c7c78303b5ef8e02ef26878d8d7",
          "md5": "0af6ac8b090244da1cf5d794c88bb9f4"
        }
      ]
    }
  ]
}