{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.2.0.aar",
          "url": "window-1.2.0.aar",
          "size": 347924,
          "sha512": "70d5157fe92db72e6e9812a770e2f29f6bbc1c9f8c9f2d2a7aa09eb86a48ddd146779f8a0340f0607b727f654a2facd5bed95439df1872310353e26461ac1144",
          "sha256": "a834c217d973112777533daf1281dab33bd778fadd2d66bebc39b5fe81a890ac",
          "sha1": "1d080d0a72684227bf6eb9af56264542708f8d16",
          "md5": "26fb8688b21b999defb43b5f0c41eb21"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window.extensions.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.2.0.aar",
          "url": "window-1.2.0.aar",
          "size": 347924,
          "sha512": "70d5157fe92db72e6e9812a770e2f29f6bbc1c9f8c9f2d2a7aa09eb86a48ddd146779f8a0340f0607b727f654a2facd5bed95439df1872310353e26461ac1144",
          "sha256": "a834c217d973112777533daf1281dab33bd778fadd2d66bebc39b5fe81a890ac",
          "sha1": "1d080d0a72684227bf6eb9af56264542708f8d16",
          "md5": "26fb8688b21b999defb43b5f0c41eb21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.2.0-sources.jar",
          "url": "window-1.2.0-sources.jar",
          "size": 146340,
          "sha512": "e1b90c5f411f7fa69c607bbe071d94f8a719c725e4e1f2bd876b496c63f9ccd5b2340fffcd46ca465241750b6ab44ebd7be101302a938611b7519ee3867206ee",
          "sha256": "9c4df6e9fc5f3edb3afa4cba0a720c707f4aa6979d5e6c626ae0596296e307d0",
          "sha1": "e9203e88b846090a7d09b8cff963be6559dadf2e",
          "md5": "6a82f8687ddde2452b3a4a8e811a145a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.2.0-versionMetadata.json",
          "url": "window-1.2.0-versionMetadata.json",
          "size": 23568,
          "sha512": "53bcbca3e4256d316975a4e57620d902fe77720c3a6875cce95c36f11ce4dd776bbc838e172c55b9cf06758b76f70068c4cfc9ba0f2c7373f89092d5374042be",
          "sha256": "a82a3e76c009196a20f5f73baab35001ce060389e6516ff27eb808d09717cb84",
          "sha1": "970a148cb4b4ef8465c6b94cdf05807457304d2d",
          "md5": "78ae16d6ec0c7fbccbc0f39f357b383b"
        }
      ]
    }
  ]
}