{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent/1.0.2/navigationevent-1.0.2.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14757970"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent.aar",
          "url": "navigationevent-android-1.0.2.aar",
          "size": 45543,
          "sha512": "80440b3cec8bb02f8ede258e3d131cf2220b63bb1ad72aa1caa3da20a044368c9a60e4ab0cbb661a2496619787af9c130d29fe835351b52c62fc589825101bd5",
          "sha256": "3fa191e3da2f6b601e944fb03a09a12278e49418dd1a9b22cd6b99f66e4283fd",
          "sha1": "c066b305bbc2ba9c5b2a86ee2e14d9093527572c",
          "md5": "e73400a8e26e6791c40c0942615d8c7a"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent.aar",
          "url": "navigationevent-android-1.0.2.aar",
          "size": 45543,
          "sha512": "80440b3cec8bb02f8ede258e3d131cf2220b63bb1ad72aa1caa3da20a044368c9a60e4ab0cbb661a2496619787af9c130d29fe835351b52c62fc589825101bd5",
          "sha256": "3fa191e3da2f6b601e944fb03a09a12278e49418dd1a9b22cd6b99f66e4283fd",
          "sha1": "c066b305bbc2ba9c5b2a86ee2e14d9093527572c",
          "md5": "e73400a8e26e6791c40c0942615d8c7a"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-android-1.0.2-sources.jar",
          "url": "navigationevent-android-1.0.2-sources.jar",
          "size": 40682,
          "sha512": "b157c6ef201e7daec4894a5f7c7dd2cc341992b03a1bca73c19fca30ff63f4c6bbb57ad4404212a86bb66475682b776a7430428016e2d1b3ad87d34a02960b3d",
          "sha256": "1dcc4746beabc29ef7601e8f6e689d360b3ac2ad63689c79868a9ddf6d7f22b8",
          "sha1": "98c91b3fc5d6dc83834f2e42ca188151e1e7533d",
          "md5": "ef2a36136baadb8a2cc9ddc0480d22c0"
        },
        {
          "name": "navigationevent-1.0.2-samples-sources.jar",
          "url": "navigationevent-android-1.0.2-samples-sources.jar",
          "size": 5859,
          "sha512": "ade557bee51aab3e41cde6381162fb98e8053ab0a9349fad48367d34bd5cebab5a76cb5081ad0f933e4a3f27ffb56f4ada3f1c5b2563acde1cad98d44d2fc1ac",
          "sha256": "df63ae9684f469f4538795438481b802b394d365566b5af25487e0eef2f4ac6f",
          "sha1": "b7d83bf2bf811c87eec0c4133cf342e08043060e",
          "md5": "3dc3a37e0a809197bcd92e7bf8e9c888"
        }
      ]
    }
  ]
}