{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.exifinterface",
    "module": "exifinterface",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "14463220"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exifinterface-1.4.2-sources.jar",
          "url": "exifinterface-1.4.2-sources.jar",
          "size": 73351,
          "sha512": "c7fe282d20c4807aedc4e544745f384f8ea738d4a0dfad0da11f8936899cd01109f59c8665bc9538f5c6e88f0c22bbcfcf072c551b215858e9d0f1825177752c",
          "sha256": "dc69c04f03e72ad38ed43774554e6612dd9ffe7299eacaab62a38df8ac2c7767",
          "sha1": "f3d68188af5162e9b308eddfa83a0ab68ac9cc9f",
          "md5": "2f266e7d230bd2b5b1bc17e5b4748409"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "exifinterface-1.4.2.aar",
          "url": "exifinterface-1.4.2.aar",
          "size": 75550,
          "sha512": "5bc8e4c325e5571b9a8d40d2901081734f8ca8210f3b16e52f3b8a5e352f2170edf859e03b6929a417da4664c3b325039b02ed1269eccac4edf3985774872431",
          "sha256": "6bb2b68682a2023c55f35f941444ffea0157947b061e4fd7606ba935e2e77425",
          "sha1": "21394465747d1a9f68297058907db6984e610772",
          "md5": "8b42aee459c783ea1b5e8121ecfbe928"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "exifinterface-1.4.2.aar",
          "url": "exifinterface-1.4.2.aar",
          "size": 75550,
          "sha512": "5bc8e4c325e5571b9a8d40d2901081734f8ca8210f3b16e52f3b8a5e352f2170edf859e03b6929a417da4664c3b325039b02ed1269eccac4edf3985774872431",
          "sha256": "6bb2b68682a2023c55f35f941444ffea0157947b061e4fd7606ba935e2e77425",
          "sha1": "21394465747d1a9f68297058907db6984e610772",
          "md5": "8b42aee459c783ea1b5e8121ecfbe928"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "exifinterface-1.4.2-versionMetadata.json",
          "url": "exifinterface-1.4.2-versionMetadata.json",
          "size": 18300,
          "sha512": "06c867f38fe901e5101da5eff834b20d845bae49ea6fe073d62421c8737d6128ef05c0580db4c680dfaddd14b0c89aaa98c5e1572627dd0ab1b99b4af26cb3ce",
          "sha256": "15162b9188690985ff1ba470b6aae0928209890f48774f4e42580aceae9e855c",
          "sha1": "b3127e3a401a1c7c78303b5ef8e02ef26878d8d7",
          "md5": "0af6ac8b090244da1cf5d794c88bb9f4"
        }
      ]
    }
  ]
}