{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window.extensions.core",
    "module": "core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 3737,
          "sha512": "e36d3531b21576e7e3ffcb72c0ecd14ae2cf1bce58cc9269055836ab4336e21a40503f009165f7cd30654397cddda7e55af28f92227c6819b52f9409ea971d7a",
          "sha256": "3100854b2dc0de5c4d88b47e1c5db30801770c821dca28189443b7624f4008ae",
          "sha1": "f755f474ef8f4ff78ba7f6cbd8146ab6a383a557",
          "md5": "3eb2456d11f878925ad796830ea05075"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 3737,
          "sha512": "e36d3531b21576e7e3ffcb72c0ecd14ae2cf1bce58cc9269055836ab4336e21a40503f009165f7cd30654397cddda7e55af28f92227c6819b52f9409ea971d7a",
          "sha256": "3100854b2dc0de5c4d88b47e1c5db30801770c821dca28189443b7624f4008ae",
          "sha1": "f755f474ef8f4ff78ba7f6cbd8146ab6a383a557",
          "md5": "3eb2456d11f878925ad796830ea05075"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.0-sources.jar",
          "url": "core-1.0.0-sources.jar",
          "size": 3620,
          "sha512": "3bd140372842b5921e1efb168e5540cf24369005fd3db0b79024fd0489450cc5bffa345ad2835aeddfa64f6ccb42f6aa99f9ee3fd4a3d7e8c0998ee15752c4fe",
          "sha256": "95d5005752d513694d7922553af4249855f05a358fff7b2016686c1f3828ebcb",
          "sha1": "cd7d30a01af4580c06bf6e5f1dd09c1471b2ece7",
          "md5": "8ea1e8355ad1d8d68f654620c93b9da1"
        }
      ]
    }
  ]
}