import 'package:flutter/material.dart';
import 'dart:async';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final appLocalizationsProvider = Provider<AppLocalizations>((ref) {
  throw UnimplementedError(
      'appLocalizationsProvider must be overridden in ProviderScope');
});

final localeProvider = StateProvider<Locale?>((ref) => null);

class AppLocalizations {
  final Locale _locale;
  Locale get locale => _locale;

  AppLocalizations(this._locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const supportedLocales = [
    Locale('en'),
    Locale('am'),
    Locale('om'),
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'login': 'Login',
      'loginTitle': 'Welcome back',
      'loginSubtitle': 'Sign in to continue managing your loads and bids.',
      'signup': 'Sign up',
      'signupTitle': 'Create your account',
      'signupSubtitle': 'Join as a driver or cargo owner to start posting and bidding loads.',
      'emailLabel': 'Email',
      'email': 'Enter your email',
      'passwordLabel': 'Password',
      'password': 'Enter your password',
      'confirmPassword': 'Confirm password',
      'passwordsNoMatch': 'Passwords do not match.',
      'nameLabel': 'Full name',
      'name': 'Enter your full name',
      'phoneLabel': 'Phone number',
      'phone': 'Enter your Phone number',
      'userType': 'User Type',
      'driverLabel': 'Driver',
      'cargoLabel': 'Cargo',
      'driver': 'Driver',
      'cargo': 'Cargo',
      'truckType': 'Select truck type',
      'truckTypeLabel': 'Truck type',
      'addressLabel': 'Business address',
      'businessAddress': 'Business Address',
      'alreadyAccount': 'Already have an account? ',
      'dontAccount': "Don't have an account yet? ",
      'post': 'Post',
      'cancel': 'Cancel',
      'continue': 'Continue',
      'newLoad': 'New Load',
      'feed': 'Feed',
      'search': 'Search',
      'language': 'Language',
      'forgotPassword': 'Forgot password',
      'forgotPasswordTitle': 'Reset password',
      'forgotPasswordBody':
          'Enter the phone number linked to your account. We will send a reset code via Telegram.',
      'sendResetLink': 'Send reset link',
      'resetEmailSent': 'If this email exists, a reset link will be sent shortly.',
      'resetEmailFailed': 'We could not start a reset. Please try again.',
      'phoneVerifyTitle': 'Verify your phone',
      'phoneVerifySubtitle':
          'We will send a one-time code via Telegram to confirm your number before sign up.',
      'phoneVerifyStepTitle': 'Step 1: Confirm in Telegram',
      'phoneVerifyStepBody':
          'Enter your phone number below. If this is your first time, we will open Telegram so you can tap Start once, and the bot will send your code there automatically.',
      'telegramLinkPending':
          'Finish the Telegram step, then come back and enter the code from the bot.',
      'telegramLinkSent':
          'Telegram opened. Tap Start in the bot chat and your code will be sent there.',
      'telegramOpenFailed':
          'Could not open Telegram automatically. Use the button below.',
      'openTelegram': 'Open Telegram',
      'sendOtp': 'Send code',
      'resendOtp': 'Resend code',
      'otpSent': 'Verification code sent.',
      'enterOtpTitle': 'Step 2: Enter the code',
      'enterOtpBody': 'Enter the 4 digit code we sent to Telegram.',
      'otpLabel': 'Verification code',
      'otpHint': 'Enter your code',
      'verifyOtp': 'Verify code',
      'otpInvalid': 'Invalid or expired code. Please try again.',
      'resetPasswordTitle': 'Reset your password',
      'resetPasswordSubtitle':
          'Request a reset code via Telegram, then enter it below to choose a new password.',
      'resetTokenLabel': 'Reset code',
      'resetTokenHint': 'Enter the code from Telegram',
      'newPasswordLabel': 'New password',
      'resetPasswordCta': 'Reset password',
      'passwordResetSuccess': 'Password updated. You can now log in.',
      'passwordResetFailed': 'Reset failed: ',
      'showPassword': 'Show password',
      'hidePassword': 'Hide password',
      'editProfile': 'Edit Profile',
      'done': 'Done',
      'bids': 'BIDS ',
      'bidNow': 'BID NOW',
      'bid': 'Bid',
      'bidPlaced': 'Bid submitted.',
      'bidAlreadyPlaced': 'You already placed a bid on this load.',
      'bidAcceptedSuccess': 'Bid accepted successfully.',
      'bidDeleted': 'Bid deleted.',
      'reply': 'Reply',
      'postComment': 'Post',
      'accept': 'Accept',
      'delpost': 'Delete Post',
      'suredelpost': 'Are you sure you want to delete this post?',
      'yes': 'Yes',
      'no': 'No',
      'DEP': 'Origin',
      'DEST': 'Destination',
      'WEIGHT': 'WEIGHT',
      'TYPE': 'TYPE',
      'PACKAGING': 'PACKAGING',
      'myLoads': 'My Loads',
      'activeLoads': 'Active Loads',
      'availableLoads': 'Available Loads',
      'noLoadsPosted': 'No posted loads yet.',
      'noLoadsAvailable': 'No loads available.',
      'status': 'Status',
      'from': 'From',
      'to': 'To',
      'retry': 'Retry',
      'refresh': 'Refresh',
      'viewAll': 'View all',
      'error': 'Error',
      'deleteLoad': 'Delete load',
      'deleteLoadConfirmation': 'Are you sure you want to delete this load?',
      'loadDeleted': 'Load deleted.',
      'home': 'Home',
      'track': 'Track',
      'profile': 'Profile',
      'usernameLabel': 'Username',
      'close': 'Close',
      'profileEditPlaceholder':
          'Profile editing UI was missing and has been restored as a placeholder.',
      'noBio': 'No bio added yet.',
      'licensePlate': 'License Plate',
      'licenseNumber': 'License Number',
      'tradeLicenseLabel': 'Trade License',
      'noLoadsPostedYet': 'No loads posted yet.',
      'userNotFound': 'User not found',
      'likesSyncMigration': 'Likes sync is being migrated to backend.',
      'myBids': 'My Bids',
      'searchLoads': 'Search Loads',
      'feedTitle': 'Freight Exchange',
      'feedSubtitle': 'Live loads from verified shippers, updated in real time.',
      'openLoads': 'Open Loads',
      'closedLoads': 'Closed Loads',
      'avgWeight': 'Avg Weight',
      'tapForDetails': 'Tap for details',
      'openForBids': 'Open for bids',
      'searchHint': 'Search by route, load type, or message',
      'welcome': 'Welcome',
      'quickActions': 'Quick actions',
      'cargoControlTitle': 'Cargo Control Center',
      'cargoControlSubtitle':
          'Post loads, review recent activity, and move quickly to tracking and profile actions.',
      'cargoQuickActionsHint': 'Post a new load or review your recent loads and bids.',
      'postFirstLoadHint': 'Post your first load to get bids from drivers.',
      'recentLoads': 'Recent loads',
      'suggestedDrivers': 'Suggested drivers',
      'suggestedDriversHint': 'We will recommend top drivers based on your routes.',
      'tapFeedToInvite': 'Tap feed to invite for bids',
      'activeJobs': 'Active jobs',
      'suggestedLoads': 'Suggested loads',
      'driverHubTitle': 'Driver Operations Hub',
      'driverHubSubtitle':
          'Monitor active jobs, discover new loads, and keep profile documents up to date.',
      'driverQuickActionsHint':
          'Find loads quickly or update your documents to get more bids.',
      'bidOnLoadsHint': 'Bid on loads to start earning.',
      'suggestedLoadsHint': 'We will suggest loads based on your routes.',
      'continueToFeed': 'Continue to feed',
      'postLoad': 'Post Load',
      'postALoad': 'Post a Load',
      'openFeed': 'Open Feed',
      'updateDocs': 'Update Docs',
      'noLoadsYet': 'No loads yet',
      'noSuggestionsYet': 'No suggestions yet',
      'noActiveJobs': 'No active jobs',
      'lastUpdated': 'Last updated',
      'logout': 'Sign out',
      'logoutConfirmation': 'Are you sure you want to sign out?',
      'resetUnavailable': 'Reset is not available right now.',
      'invalidEmail': 'Enter a valid email address.',
      'required': 'Required',
      'passwordMin': 'Password must be at least 8 characters.',
      'termsRequired': 'Please accept Terms of Service.',
      'privacyRequired': 'Please accept the Privacy Policy.',
      'weight': 'Weight',
      'unit': 'Unit',
      'loadType': 'Load Type',
      'startLocation': 'Start Location',
      'destination': 'Destination',
      'startLocationHint': 'City, region, or area',
      'destinationHint': 'City, region, or area',
      'packaging': 'Packaging',
      'loadDescription': 'Load Description',
      'shareLoadDetails': 'Share load details',
      'shareLoadDetailsHint':
          'Add clear route and cargo info to get better bids faster.',
      'searchAll': 'All',
      'searchGeneral': 'General',
      'refreshing': 'Refreshing',
      'includeClosedLoads': 'Include closed loads',
      'showingOpenOnly': 'Showing open loads only.',
      'showingAllLoads': 'Showing all loads.',
      'trackDriver': 'Track Driver',
      'messageCarrier': 'Message Carrier',
      'messageShipper': 'Message Shipper',
      'inAppChat': 'In-App Chat',
      'callDriver': 'Call Driver',
      'callShipper': 'Call Shipper',
      'markDelivered': 'Mark Delivered',
      'reportIssue': 'Report Issue',
      'cannotCompleteDeliveryMissingBid': 'Cannot complete delivery: missing accepted bid reference.',
      'failedCompleteDelivery': 'Failed to complete delivery: ',
      'issueReported': 'Issue reported. Support can now review this load.',
      'failedReportIssue': 'Failed to report issue: ',
      'noPhoneForMessaging': 'No phone number available for messaging.',
      'unableOpenMessaging': 'Unable to open the messaging app.',
      'noPhoneForCalling': 'No phone number available for calling.',
      'unableOpenDialer': 'Unable to open the phone dialer.',
      'confirmCallTitle': 'Confirm call',
      'confirmCallBody': 'Call this number?',
      'confirmMessageTitle': 'Confirm message',
      'confirmMessageBody': 'Message this number?',
      'rateDriver': 'Rate the Driver',
      'rateDriverPrompt': 'Please rate your experience with the driver.',
      'optionalFeedback': 'Optional feedback',
      'submit': 'Submit',
      'thanksFeedback': 'Thanks for your feedback!',
      'failedSubmitRating': 'Failed to submit rating. Please try again.',
      'proofOfDelivery': 'Proof of Delivery',
      'receiverName': 'Receiver name',
      'deliveryNotes': 'Delivery notes',
      'photoUrlOptional': 'Photo URL (optional)',
      'receiverAndNotesRequired': 'Receiver name and delivery notes are required.',
      'completeDelivery': 'Complete Delivery',
      'reportShipmentIssue': 'Report Shipment Issue',
      'issueCategory': 'Issue category',
      'issueDetailsPrompt': 'What happened?',
      'pleaseAddIssueDetails': 'Please add issue details.',
      'delay': 'Delay',
      'damagedGoods': 'Damaged goods',
      'communicationIssue': 'Communication',
      'paymentIssue': 'Payment',
      'otherIssue': 'Other',
      'bidUpdatedSuccess': 'Bid updated successfully!',
      'bidPlacedSuccess': 'Bid placed successfully!',
      'bidAmountLabel': 'Bid Amount',
      'notesOptional': 'Notes (optional)',
      'placeBid': 'Place Bid',
      'updateBid': 'Update Bid',
      'availableLoad': 'Available Load',
      'bidsSoFar': 'bids so far',
      'openStatus': 'Open',
      'enterBidAmount': 'Enter bid amount',
      'bidSubmitted': 'Bid submitted.',
      'yourBid': 'Your Bid',
      'submitBid': 'Submit Bid',
      'liveLocationError': 'Unable to load live location right now.',
      'threadNotFound': 'Thread not found.',
      'noBidsYet': 'No bids yet.',
      'noBidsPlacedYet': 'You have not placed any bids yet.',
      'acceptBid': 'Accept',
      'delete': 'Delete',
      'noItemsYet': 'No items yet.',
      'typeLabel': 'Type',
      'ratingLabel': 'Rating',
      'acceptedLoads': 'Accepted Loads',
      'submittingBid': 'Submitting bid...',
      'bidUpdated': 'Bid updated!',
      'bidSubmittedMsg': 'Bid submitted!',
      'enterValidBidAmount': 'Please enter a valid bid amount.',
      'statusUpdatedTo': 'Status updated to',
      'offlineStatusQueued':
          'You appear offline. Status queued and will sync automatically.',
      'currentStatusLabel': 'Current Status',
      'chat': 'Chat',
      'noMessagesYet': 'No messages yet. Start the conversation.',
      'typeMessage': 'Type message...',
      'send': 'Send',
      'weightMustBeGreater': 'Weight must be greater than zero',
      'loadPostedSuccess': 'Load posted successfully!',
      'viewFeed': 'View feed',
      'loadPostFailed': 'Failed to post load: ',
      'loadIndex': 'Load',
      'bidsCount': 'bids',
      'pickup': 'Pickup',
      'delivery': 'Delivery',
      'back': 'Back',
      'failedToLoadBids': 'Failed to load bids: ',
      'failedToSendMessage': 'Failed to send message: ',
      'agreeTerms': 'I agree to the Terms of Service',
      'agreePrivacy': 'I agree to the Privacy Policy',
      'failedAcceptBid': 'Failed to accept bid: ',
      'failedDeleteBid': 'Failed to delete bid: ',
      'alreadyBidUpdateNotice':
          'You already bid on this load. Editing this form updates your current bid.',
      'enterAmount': 'Enter amount',
      'enterValidAmount': 'Enter a valid amount',
      'estimatedPlatformFee': 'Estimated platform fee (5%)',
      'estimatedNetPayout': 'Estimated net payout',
      'acceptedCarriers': 'Accepted Carriers',
      'manage': 'Manage',
      'currentStatus': 'Current Status',
      'timeline': 'Timeline',
      'timeUnavailable': 'time unavailable',
      'justNow': 'Just Now',
      'ago': 'ago',
      'yesterday': 'Yesterday',
      'Jan': 'Jan',
      'Feb': 'Feb',
      'Mar': 'Mar',
      'Apr': 'Apr',
      'May': 'May',
      'Jun': 'Jun',
      'Jul': 'Jul',
      'Aug': 'Aug',
      'Sep': 'Sep',
      'Oct': 'Oct',
      'Nov': 'Nov',
      'Dec': 'Dec',
      'tourQuickTitle': 'Quick tour',
      'tourQuickSubtitle':
          'A guided walkthrough of the places you will use most in your first sessions.',
      'tourStepLabel': 'Step',
      'tourSkip': 'Skip',
      'tourBack': 'Back',
      'tourNext': 'Next',
      'tourStartExploring': 'Start exploring',
      'tourReplayTitle': 'Replay quick tour',
      'tourReplaySubtitle':
          'Walk through the key tabs, guided actions, and verification steps again.',
      'tourOpenHome': 'Open home',
      'tourOpenFeed': 'Open feed',
      'tourOpenMyBids': 'Open my bids',
      'tourOpenVerification': 'Open verification',
      'tourOpenPost': 'Open post load',
      'tourCargoHomeTitle': 'Home keeps the day organized',
      'tourCargoHomeBody':
          'Start on Home to see quick actions, recent loads, and suggested drivers without hunting through tabs.',
      'tourCargoFeedTitle': 'Feed shows the live market',
      'tourCargoFeedBody':
          'Browse fresh route activity in Feed when you want a wider view before posting a load.',
      'tourCargoVerificationTitle': 'Verification unlocks posting',
      'tourCargoVerificationBody':
          'Upload your national ID and track approval so posting stays smooth once you are ready to publish.',
      'tourCargoPostTitle': 'Post loads from one clear action',
      'tourCargoPostReadyBody':
          'Once approved, use the post action to publish a load and start collecting bids quickly.',
      'tourCargoPostLockedBody':
          'Your post action is ready, but verification needs approval first. Open verification now so posting is unlocked.',
      'tourDriverHomeTitle': 'Home surfaces your next jobs',
      'tourDriverHomeBody':
          'Use Home for suggested loads, active work, and shortcuts when you want the fastest overview.',
      'tourDriverFeedTitle': 'Feed is where discovery happens',
      'tourDriverFeedBody':
          'Open Feed to scan fresh loads, compare routes, and jump into the ones that fit your truck.',
      'tourDriverBidsTitle': 'My Bids keeps offers organized',
      'tourDriverBidsBody':
          'Track every pending or accepted offer in one place so you can follow up without digging back through the feed.',
      'tourDriverVerificationTitle': 'Verification unlocks bidding',
      'tourDriverVerificationBody':
          'Upload your national ID and driver\'s license to unlock bidding and keep your profile ready for approval.',

      // ...add more as needed
    },
    'om': {
      'login': 'Login',
      'signup': 'Akawntii bana',
      'email': 'Imelii kee galchi',
      'password': 'Paswordii kee galchi',
      'name': 'Maqaa kee galchi',
      'phone': 'Telefoonii kee galchi',
      'userType': 'Meeshaa moo Konkolaataa qabduu?',
      'driver': 'Konkolaataa kan qabu',
      'cargo': 'Mesha kan qabu',
      'truckType': 'Gosa konkolaataa filadhu',
      'alreadyAccount': 'Akkawotii qabduu? ',
      'dontAccount': 'Akkawotii hin qabduu? ',
      'post': 'Maxxansi',
      'cancel': 'Dhiisi',
      'newLoad': 'Fe’umsaa Haaraa',
      'feed': 'Feedii',
      'search': 'Barbaadi',
      'forgotPassword': 'Paswordii Irranfadhe',
      'editProfile': 'Piroofaayilii Gulaali',
      'done': 'Xumurame',
      'bids': 'Baayina caalbaasii:',
      'bidNow': 'Caalbaasii',
      'reply': 'Deebisi',
      'postComment': 'Maxxansi',
      'accept': 'Fudhadhu',
      'delpost': 'Postii kana haqi',
      'suredelpost': 'Postii kana haquu barbaaddu?',
      'yes': 'Eeyyee',
      'no': 'Lakki',
      'DEP': 'Bakka Kaumsaa',
      'DEST': 'Iddoo deemu',
      'WEIGHT': 'Ulfaatina',
      'TYPE': 'Gosa',
      'PACKAGING': 'Qophii',
      'myLoads': 'My Loads',
      'activeLoads': 'Active Loads',
      'availableLoads': 'Available Loads',
      'noLoadsPosted': 'No posted loads yet.',
      'noLoadsAvailable': 'No loads available.',
      'status': 'Status',
      'from': 'From',
      'to': 'To',
      'retry': 'Retry',
      'refresh': 'Refresh',
      'acceptedCarriers': 'Accepted Carriers',
      'manage': 'Manage',
      'currentStatus': 'Current Status',
      'timeline': 'Timeline',
      'timeUnavailable': 'time unavailable',
      'justNow': 'Amma',
      'ago': 'Dura',
      'yesterday': 'Kaleessa',
      'Jan': 'Ama',
      'Feb': 'Gur',
      'Mar': 'Bit',
      'Apr': 'Ebla',
      'May': 'Cam',
      'Jun': 'Wax',
      'Jul': 'Ado',
      'Aug': 'Hag',
      'Sep': 'Ful',
      'Oct': 'Onk',
      'Nov': 'Sad',
      'Dec': 'Mud',

      // ...add more as needed
    },
    'am': {
      'login': 'Login',
      'signup': 'መመዝገብ',
      'email': 'ኢሜይልዎን ያስገቡ',
      'password': 'የይለፍ ቃል ያስገቡ',
      'name': 'ሙሉ ስምዎን ያስገቡ',
      'phone': 'ስልክ ቁጥርዎን ያስገቡ',
      'userType': 'የተጠቃሚ አይነት',
      'driver': 'መኪና ያለው',
      'cargo': 'የሚጓጓዝ ጭነት ያለው',
      'truckType': 'የተሸከርካሪ አይነት ይምረጡ',
      'alreadyAccount': 'አካውንት አለዎት?',
      'dontAccount': 'አካውንት አልከፈቱም?',
      'post': 'ለጥፍ',
      'cancel': 'ሰርዝ',
      'newLoad': 'አዲስ ጭነት',
      'feed': 'መጠቀሚያ',
      'search': 'ፈልግ',
      'forgotPassword': 'የይለፍ ቃል አስታውሱም',
      'editProfile': 'መገለጫ አስተካክል',
      'done': 'ተጠናቀቀ',
      'bids': 'የተጫራቾች ብዛት:',
      'bidNow': 'አሁን ይጫረቱ',
      'reply': 'መልስ ስጥ',
      'postComment': 'ለጥፍ',
      'accept': 'ተቀበል',
      'delpost': 'ይህን ሰርዝ',
      'suredelpost': 'ይህን መሰረዝ ይፈልጋሉ?',
      'yes': 'አዎ',
      'no': 'አይ',
      'DEP': 'መነሻ ቦታ',
      'DEST': 'መድረሻ ቦታ',
      'WEIGHT': 'ክብደት',
      'TYPE': 'አይነት',
      'PACKAGING': 'መጠቀለያ',
      'myLoads': 'የእኔ ጭነቶች',
      'activeLoads': 'በሂደት ያሉ ጭነቶች',
      'availableLoads': 'ያሉ ጭነቶች',
      'noLoadsPosted': 'እስካሁን የተለጠፈ ጭነት የለም።',
      'noLoadsAvailable': 'ያለ ጭነት የለም።',
      'status': 'ሁኔታ',
      'from': 'ከ',
      'to': 'ወደ',
      'retry': 'ዳግም ሞክር',
      'refresh': 'አድስ',
      'acceptedCarriers': 'የተቀበሉ አጓጓዦች',
      'manage': 'አስተዳድር',
      'currentStatus': 'የአሁኑ ሁኔታ',
      'timeline': 'የሂደት ታሪክ',
      'timeUnavailable': 'ጊዜ አይገኝም',
      'justNow': 'አሁን',
      'ago': 'በፊት',
      'yesterday': 'ትናንት',
      'Jan': 'Jan',
      'Feb': 'Feb',
      'Mar': 'Mar',
      'Apr': 'Apr',
      'May': 'May',
      'Jun': 'Jun',
      'Jul': 'Jul',
      'Aug': 'Aug',
      'Sep': 'Sep',
      'Oct': 'Oct',
      'Nov': 'Nov',
      'Dec': 'Dec',
      // ...add more as needed
    }
  };

  String tr(String key) {
    return _localizedValues[_locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    // Add your supported locales here
    return ['en', 'am', 'om'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    // Implement your loading logic here
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// This file only provides localization utilities and the provider.
