{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.7.0.aar",
          "url": "lifecycle-livedata-core-2.7.0.aar",
          "size": 11311,
          "sha512": "d716ae46e8ac2a19cd31575e4673c31d01f74ba56a1a03b94221869a867a23731d64cc1876ee16cbc0d452307508dea5cb106d857f47baee11f9523e471c1d9e",
          "sha256": "af8e11b87e030d6e3107ed39adcf01fa10d6259eb15c43cba6e7b4e3ffaedf27",
          "sha1": "d95c9c0b74a6b9882c416c688f6cf201dc416bed",
          "md5": "ab8db7c4a726434248ffdf9e32f126aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.7.0.aar",
          "url": "lifecycle-livedata-core-2.7.0.aar",
          "size": 11311,
          "sha512": "d716ae46e8ac2a19cd31575e4673c31d01f74ba56a1a03b94221869a867a23731d64cc1876ee16cbc0d452307508dea5cb106d857f47baee11f9523e471c1d9e",
          "sha256": "af8e11b87e030d6e3107ed39adcf01fa10d6259eb15c43cba6e7b4e3ffaedf27",
          "sha1": "d95c9c0b74a6b9882c416c688f6cf201dc416bed",
          "md5": "ab8db7c4a726434248ffdf9e32f126aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.7.0-sources.jar",
          "url": "lifecycle-livedata-core-2.7.0-sources.jar",
          "size": 6941,
          "sha512": "ab482d12daa46c389be080cba586fc93e9dcb909b4285b927e119ad1d1a475d80417c12d4e67e5c3bcb8a8b97da2f51a960025e50277c23c56ff8ddb1154be62",
          "sha256": "5ed0b2f1e01bed494c9d70558a6b1fca295c32f47e5d9e652b316e8989d9689c",
          "sha1": "148c40c69e28eb19bdf817bef6e7b0f24bfa51f9",
          "md5": "5896f6d656293e503e2f8249df6c1347"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.7.0"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.7.0-versionMetadata.json",
          "url": "lifecycle-livedata-core-2.7.0-versionMetadata.json",
          "size": 1296,
          "sha512": "dd030a9a039ebf2bd50742bbbafedea854982465b251f09bc3cf3ba0dee091aed21a84b4f4b027ad2b2bbeb61175583588391a17e85d1a8b0caacec58bc4e424",
          "sha256": "74ba4fdab7845beac5e3f33efdb37e3d6d46b225859fa6199eda663d28f9b465",
          "sha1": "fe2ddf505a0d7da1f69588c8b58bf0442362178b",
          "md5": "62dac190e042927b4830cb976f9ae889"
        }
      ]
    }
  ]
}