{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-java",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.2.0.aar",
          "url": "window-java-1.2.0.aar",
          "size": 11547,
          "sha512": "0a9342a6d54b79c828c948d031be4188ebb5aa02acd9599198fcdc712552b2871affe98f863771a75a83a0b93eaa1e7987c2204d7514946f5680c3aa8e3ea533",
          "sha256": "e3defb5ee3857757505d7ad66275dc3a0b014169301b89d6e4eec03b0e45bcab",
          "sha1": "924d0a3ca93fac4acb32c6a972e9fa1e283f1f07",
          "md5": "565b947e4c8865408cf46c13101d6f7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.2.0.aar",
          "url": "window-java-1.2.0.aar",
          "size": 11547,
          "sha512": "0a9342a6d54b79c828c948d031be4188ebb5aa02acd9599198fcdc712552b2871affe98f863771a75a83a0b93eaa1e7987c2204d7514946f5680c3aa8e3ea533",
          "sha256": "e3defb5ee3857757505d7ad66275dc3a0b014169301b89d6e4eec03b0e45bcab",
          "sha1": "924d0a3ca93fac4acb32c6a972e9fa1e283f1f07",
          "md5": "565b947e4c8865408cf46c13101d6f7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.2.0-sources.jar",
          "url": "window-java-1.2.0-sources.jar",
          "size": 6191,
          "sha512": "759cb7a5d7ad7394b50abbde310ff0ef4b78ef85c7cbaab50808ae90b80fc52b411f88d5ec1f50706e6c8dec4139ceab2f64a3eef7a332c2d135fed400399612",
          "sha256": "b257a29441778b87c704f39b2abb957d6a82ff639dec45f51811f69627576d1b",
          "sha1": "52a2c7fcfb18896414f8ec49b2b1445ab2c0b460",
          "md5": "ce34292f8870c40cd49916cb3ee26f09"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.2.0-versionMetadata.json",
          "url": "window-java-1.2.0-versionMetadata.json",
          "size": 1797,
          "sha512": "6c67da1aea15855c7a46b2d9801a3c1833baa286f196d5e60a602494be8cd29c940a3bd43098639162b29df127cb8c52d4e5a65e1aba26dbb89d10c815c6b473",
          "sha256": "a8568a4d33696146ce382f891bed3672ccd43ecab637bfbe9b140353a9a21398",
          "sha1": "575d9826371196c7849cf1ab115b5454749f5748",
          "md5": "dc725615ed7cba8085b8671fa1dd0d0f"
        }
      ]
    }
  ]
}